version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: greencop
      POSTGRES_USER: nafra
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nafra -d greencop"]
      interval: 5s
      timeout: 5s
      retries: 5

  customers-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    command: >
      sh -c "
        cd customers &&
        alembic upgrade head &&
        cd .. &&
        uvicorn main:app --host 0.0.0.0 --port 8080
      "

volumes:
  postgres_data:
