"""Add room and sensor tables

Revision ID: 131d5d95f555
Revises: 10d9e0b4de0c
Create Date: 2025-09-18 20:26:51.658702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "131d5d95f555"
down_revision: Union[str, Sequence[str], None] = "10d9e0b4de0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
