apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: gcr.io/ancient-vortex-478017-d1/customers:latest
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_KEY
          value: "a_very_secret_key"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: DB_URL
          value: "postgresql://nafra:test@postgres:5432/greencop"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  selector:
    app: customers
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
