on:
  push:
    branches:
      - main


jobs:
  setup-env:
    name: "tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m pip install pytest
          uv sync
      - name: Run tests
        run: |
          PYTHONPATH=./services uv run pytest services/customers/tests -vv -x


