on:
  push:
    branches: [main]

jobs:
  setup-env:
    name: "tests"
    env:
        DB_URL: ${{ secrets.DB_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
    runs-on: "ubuntu-latest"

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ secrets.PG_PWD }}
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_DB: ${{ secrets.PG_DB }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m pip install pytest
          uv sync
      - name: Run tests

        run: |
          PYTHONPATH=./services uv run pytest services/customers/tests -vv -x


